#ifndef FILETRANSFERCONSTANTS_H
#define FILETRANSFERCONSTANTS_H

#include <QtGlobal>

constexpr qint64 FILE_TRANSFER_CHUNK_SIZE = 256 * 1024;
constexpr qint64 FILE_TRANSFER_MAX_CHUNK_SIZE = 1024 * 1024;
constexpr int FILE_TRANSFER_MAX_IN_FLIGHT_CHUNKS = 64;
constexpr int FILE_TRANSFER_ACK_BATCH_SIZE = 1;
constexpr qsizetype FILE_TRANSFER_WRITE_BATCH_BYTES = 1024 * 1024;

#endif // FILETRANSFERCONSTANTS_H
